Feat/#1
team-balt/easier-dodam pull request #6
Opened 2024-11-25 13:54 UTC by GayeongKimm

2024-11-25 14:07 UTC, 8954sood requested changes

2024-11-25 14:07 UTC, 8954sood commented on lib/feature/night_study/night_study.dart
> +      },
사용하지 않은 함수는 지워주세요.

2024-11-25 14:07 UTC, 8954sood commented on lib/feature/night_study/night_study.dart
> +              builder: (context, provider, child) {
이미 위에 Consumer를 통하여 ViewModel을 주입받은 것으로 보입니다.
지워주세요.

2024-11-25 14:07 UTC, 8954sood commented on lib/feature/night_study/night_study_viewmodel.dart
> +  }
현재, 지우고 난뒤 notifyListeners 를 통해 view에 상태를 반영해야할 것 같습니다.

2024-11-26 02:01 UTC, 8954sood requested changes

2024-11-26 02:01 UTC, 8954sood commented on lib/main.dart
> +    });
2초는 너무 긴것 같습니다,
그리고 현재 로컬에 토큰 여부에 따라 loginRoute 또는 outSleepingRoute로 가게 만들어주세요.

2024-11-26 02:37 UTC, 8954sood requested changes

2024-11-26 02:37 UTC, 8954sood commented on lib/remote/core/core_client.dart
> +  }
해당 메서드는 CoreClient에 있는 것은 부적절해 보입니다.
StorageManager에 만들어주세요.

2024-11-26 02:52 UTC, 8954sood approved these changes

2024-11-26 03:17 UTC, priverg approved these changes

2024-11-26 03:22 UTC, merged